---
- hosts: sites
  remote_user: ansible
  tasks:
  - name: Pull latest version
    git: repo=git@github.com:OisinA/oisinaylward.me.git dest=oisinaylward.me
  # - name: Convert HTZ to HTML
  #   shell: 
  #     cmd: /bin/zephyrus index.htz index.html
  #   args:
  #     chdir: oisinaylward.me
  - name: Create public_html
    file:
      path: public_html
      state: directory
  - name: Move index.html
    shell:
      cmd: mv oisinaylward.me/index.html public_html/index.html
  - name: Move images
    shell:
      cmd: mv oisinaylward.me/*.jpg public_html/
