name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Build image
      uses: "actions/docker/cli@master"
      with:
        args: "build -t oisinaylward.me:5000/personal-website ."
    - name: Add registry
      run: echo '{\n"insecure-registries": ["oisinaylward.me:5000"]\n}' >> /etc/docker/daemon.json
    - name: Push image
      uses: "actions/docker/cli@master"
      with:
        args: "push oisinaylward.me:5000/personal-website"
