name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Build image
      uses: "actions/docker/cli@master"
      args: "build -t oisinaylward.me:5000/personal-website ."
    - name: Push image
      uses: "actions/docker/cli@master"
      args: "push oisinaylward.me:5000/personal-website"
