name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: Login
        run: docker login docker.pkg.github.com -u {{ secrets.DOCKER_USERNAME }} -p {{ secrets.DOCKER_PASSWORD }}
      - name: Build
        run: docker build -t docker.pkg.github.com/OisinA/oisinaylward.me/oisinaylward.me .
      - name: Push
        run: docker push docker.pkg.github.com/OisinA/oisinaylward.me/oisinaylward.me
